### ISSUE TITLE
Build is failing on OS X 10.11

### ISSUE THREAD

**Issue by schultyy** [semantic-rs/semantic-rs#100]
It looks like there are issues when semantic-rs gets built on OS X 10.11 and up because of openssl. Apparently OS X doesn't ship OpenSSL headers anymore.

**Comment by schultyy** [comment]
Possible solutions:

- `brew link --force openssl`

**Comment by emig** [comment]
OPENSSL_INCLUDE_DIR=`brew --prefix openssl`/include OPENSSL_LIB_DIR=`brew --prefix openssl`/lib  cargo run -- -p ../test-project

**Comment by Hoverbear** [comment]
```
> brew link --force openssl
Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

**Comment by badboy** [comment]
Hmpf, I have openssl. The folks at hyper had similar problems. I will lookup how the decided to work around this.

**Comment by schultyy** [comment]
I did some research and found these two options:

```
OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include DEP_OPENSSL_INCLUDE=/usr/local/opt/openssl/include
```

and:

```
OPENSSL_ROOT_DIR=/usr/local/opt/openssl/
```
