### ISSUE TITLE
Integration test error in OS X

### ISSUE THREAD

**Issue by emig** [semantic-rs/semantic-rs#103]
The script that runs the integration is not compatible with OS X.
The tests fails on commands `readlink -f` and `cp -ar`, since those have different options interface  on that platform.

- readlink
fails with `readlink: illegal option -- f`

- `cp -ar` 
fails with `cp: the -R and -r options may not be specified together.`  The flag -a expands to -pPR in OS X, there the conflict.

**Comment by badboy** [comment]
Yey for not being POSIX.
I fixed a similar thing once for the Redis install script, I can just re-use that, then we do not even need readlink's non-POSIX `-f` option anymore.
