### ISSUE TITLE
Is it possible to only use the automatic version incrementing and changelog generation without pushing the crate?

### ISSUE THREAD

**Issue by SirWindfield** [semantic-rs/semantic-rs#125]
It's mostly for a project of mine that uses a lot of small crates as some sort of plugins. And I just don't want to handle the versioning on my own. As I always use Angular style commit messages, this would come in handy.

**Comment by badboy** [comment]
In theory it should be, we once implemented a "no-release" mode by [passing the `--release=no` flag](https://github.com/semantic-rs/semantic-rs/blob/609bf340ccead5fe479412ca2a7be300e82d3f5c/src/main.rs#L58).
However, I haven't used semantic-rs in a while, so I can't tell you if it actually works as it should.

**Comment by schultyy** [comment]
Confirming what @badboy said above. If you don't pass `release` or `--release=no` we only build locally and don't push anything to crates.io and GitHub.
I'm closing this but feel free to reopen if anything is unclear.
