### ISSUE TITLE
Attach binaries to release

### ISSUE THREAD

**Issue by schultyy** [semantic-rs/semantic-rs#132]
As a user I want to attach freshly built binaries to a new release on GitHub so that other users can directly download them from there. 
This should be optional since this is a use case only relevant for binaries and not for libraries.

**Comment by badboy** [comment]
Oops, just filed #133 which is for semantic-rs itself.
I don't think it should be semantic-rs' tasks to attach those files though, [trust](https://github.com/japaric/trust/) is a pretty good start for it

**Comment by schultyy** [comment]
Agreed! Closing this one in favor of #133.
