### ISSUE TITLE
Problems compiling

### ISSUE THREAD

**Issue by mainrs** [semantic-rs/semantic-rs#136]
I am currently trying to get `semantic-rs` to compile. I've read that the OpenSSL versions conflict so I installed the older package `openssl-1.0` to make sure to compile against the right version of SSL.

Running the following command still fails though: 
```
OPENSSL_LIB_DIR=/usr/lib/openssl-1.0 OPENSSL_INCLUDE_DIR=/usr/include/openssl-1.0 cargo install semantic-rs
```

At the very end I get [this](https://gist.github.com/SirWindfield/0c417d38d92cedd6e3e9dc21d847605b) error message displayed. Any idea how to make semantic-rs compile?

#### System information
__OS:__ Arch Linux
__OpenSSL version:__ OpenSSL 1.0.2q  20 Nov 2018
__Rust version:__ rustc 1.33.0-nightly (14b96659e 2018-12-25)
__Cargo version:__ cargo 1.33.0-nightly (2cf1f5dda 2018-12-11)

**Comment by badboy** [comment]
Probably just needs an update of our openssl dependency.
I won't have access to my Arch Linux machine for another week, so can't really fix & test before that.

**Comment by mainrs** [comment]
Do you guys have tests that cover some use-cases? I can fork and update the dependency but if there are no automated tests then I'm not really sure what to look for.

**Comment by badboy** [comment]
Sure, we even have CI running on every push and PR: https://github.com/semantic-rs/semantic-rs/blob/master/.travis.yml

You can run tests locally: https://github.com/semantic-rs/semantic-rs#running-the-tests
(or just run `make test`)

**Comment by badboy** [comment]
For the OpenSSL thing it should mostly be a "does it compile?" test ;)
