### ISSUE TITLE
Run fails when project doesn't follow commit guidelines

### ISSUE THREAD

**Issue by schultyy** [semantic-rs/semantic-rs#19]
Given a project where the commit message format does not follow the Angular.js commit message format.
Right now execution fails with 
```bash
[1] % cargo run -- -p ../test-project
     Running `target/debug/semantic-rs -p ../test-project`
semantic.rs 🚀
Analyzing your repository
Current version: 0.6.0
Analyzing commits
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseError("Parse error")', ../src/libcore/result.rs:736
An unknown error occurred

To learn more, run the command again with --verbose.
```

Instead it should print out a meaningful error message.

**Comment by badboy** [comment]
Can you provide the test-project or its commit messages? I can't reproduce it right now.

**Comment by schultyy** [comment]
I tried with avm and figured out what went wrong. It didn't fail because of the commit message guidelines but because one tag name was not in the expected format (`v05.1` instead of `v0.5.1`). The problem occurs here: https://github.com/semantic-rs/commit-walker/blob/a42918a38f2d4102a6658a28291d91eec66a8081/src/lib.rs#L34

**Comment by schultyy** [comment]
Commit-Walker now fails with an `expect` in case the tag name is malformed: https://github.com/semantic-rs/commit-walker/commit/d3c05056edb662912c3ce774060c981e220f1c89

**Comment by badboy** [comment]
It's an improvement, but I guess we can just skip tags that don't parse instead of failing

**Comment by schultyy** [comment]
I agree
