### ISSUE TITLE
default behavior if no args passed

### ISSUE THREAD

**Issue by schultyy** [semantic-rs/semantic-rs#43]
I'm currently thinking of what should happen if the user passes no args. Right now semantic-rs takes the current directory as working directory into account. But when installed on a system and not run via cargo I guess this won't work anymore because the current dir is then something like `/usr/local/` or `~/.bin`. My proposal here is that the user just gets the help text printed and they need to pass a path to a repository explicitly.

**Comment by badboy** [comment]
If it is installed in a directory and executed from your project's folder (because it is in the `PATH`), the current working directory will be the project's folder just as expected. Though as said in #39 it should likely only run dry.

**Comment by badboy** [comment]
Dry-run is now the default
