### ISSUE TITLE
Add support for non library projects

### ISSUE THREAD

**Issue by schultyy** [semantic-rs/semantic-rs#59]
Right now, we only support libraries by ignoring `Cargo.lock` when performing version upgrades. This is fine for libraries, since they have `Cargo.lock` ignored.
For Commandline applications, we need to run a `cargo build` after increasing the version number to ensure that a new version number is written in `Cargo.lock` as well.
We need to figure out if Cargo.lock needs to be committed afterwards or if it should be skipped.

**Comment by badboy** [comment]
http://alexcrichton.com/git2-rs/git2/struct.Repository.html#method.status_should_ignore – We can check if Cargo.lock should be added :)

**Comment by badboy** [comment]
Fixed for now with the most basic support. We might want to re-visit this to provide better error handling
