### ISSUE TITLE
Expand relative project path

### ISSUE THREAD

**Issue by schultyy** [semantic-rs/semantic-rs#63]
When a user passes a relative path to `-p` like this:

```bash
$ semantic-rs -p ../test -w
```
the path needs to be expanded to ensure that all functionalities work correctly. Because right now `cargo package` and `cargo fetch` do not work correctly with relative paths passed

**Comment by badboy** [comment]
http://doc.rust-lang.org/stable/std/fs/fn.canonicalize.html
