### ISSUE TITLE
Repository not hosted on GitHub

### ISSUE THREAD

**Issue by schultyy** [semantic-rs/semantic-rs#79]
If the user does not host their source code on GitHub but somewhere else we cannot create a release there. Therefor we need to check that first before we create a release.

**Comment by badboy** [comment]
We now support pushing to ssh uris as well, so all we need to do is disable the creation of a release.

**Comment by schultyy** [comment]
Yep. I already started to work on this one. Need to push my changes though. But I guess after the open PRs get merged I need to see how to ingegrate my changes.

**Comment by schultyy** [comment]
Tested this one with a repository hosted on Bitbucket. Works fine so far.
