### ISSUE TITLE
HTTP remotes require authentication

### ISSUE THREAD

**Issue by schultyy** [semantic-rs/semantic-rs#81]
Given the case a repository was cloned via HTTP remote. semantic-rs runs and tries to push changes back it currently fails with:

```
#...
Creating annotated git tag
Pushing new commit and tag
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore/option.rs:330
Process didn't exit successfully: `target/debug/semantic-rs -p /Users/janschulte/projects/semantic-rs/test-rs -w` (exit code: 101)
```
This happens because in this case the remote wants username and password from the user but semantic-rs doesn't show the prompt. When I `cd` into the repository's directory and `git push` I get asked for username and password.

The remote in this case is not GitHub so working with the GitHub API Token is not an option.

**Comment by schultyy** [comment]
One option to work around this would be the usage of `~/.netrc`

**Comment by badboy** [comment]
The thing is: do we want to automate everything? In that case I'd say we have to reject things that needs explicit user input.
A GitHub token or ssh key (via ssh-agent) can be given via the environment, I'm not so sure about the user/password thing.

**Comment by schultyy** [comment]
I opened #90 for better ssh support. I suppose we could close this one then.

**Comment by schultyy** [comment]
Yep I would go for ssh support here.
