### ISSUE TITLE
Link to Contributor Covenant Version?

### ISSUE THREAD

**Issue by 1000miles** [semantic-rs/semantic-rs#83]
Dear all, as discussed with @schultyy I'd like to suggest to link to a specific version of the contributor covenant in your README file, e.g. http://contributor-covenant.org/version/1/4/ (latest version). What do you think?

After you have done this, I would love to add your project here, if that is okay?
https://github.com/1000miles/coc-collections

**Comment by badboy** [comment]
I changed the link in the README to point to the used version 1.3.0 for now. I will check the latest version later.

Feel free to add it to that list. :)
